script: bash ./deploy.sh
language: node_js
node_js:
  - '5'
env:
  global:
    - GH_REF: github.com/TondaHack/simple-blog.git
    - secure: "IYtPFSSe0pWPs9utF4dIttDzr5i/7KYoulWuQ5R3yhWBI5GvlfCVAHrOoHVuJe9NU3ErcxU+7L3r/GZxbPEKli0Up4WoMLFUt13bZO8aqsJ2vujxlSKdyQIny4fB/0Trb/kW12BcmrD5fXAn/nedr465rc4ptOt1MBg5P7rHXRGXySspI+xeulNzvvdYX50JYTefxuslJqp4jH7nWy+X7tSoEhH+Yc8QCYFfRKbs45UdFfmqmewu6LQ/mRPO1+NME8PHm+Kb8OOrbbcuKbU4o121CP/qITYGPg+j9gOIsU6mX8//4oezEfcp+z1xuhFJ+DhoSeN/NNGLkFvio4QH4cJtao6kO3oWtVafkn4DUnTvKtt4gr01cEYSNFvTVf+Zz/kcWbYRTZto/IEsEGHzk4+teddMPuNnX55kHh5/C0v9np7CDqZEGTYZ0OuYME6fw/agpxllKSIKPjI8/9jBz0UIVe8siPlmeIwuohM3SK6D1AyNSkw0tCrFABlIaOQh87g99R+e3ErKYJkgl6biJpESIJ225si51jC/xNPbtunQpcFkQdhy86IjwxlSqdaFuyXQmHjRIfDfhAH399jwLR5YD+R8+p8KrnwqCDg4+OjLhSry+5nLFGcVhASoB09J5j14mf7ItbNNOtKkNTL5D91aMssMvCdkD+QSzaggVPw="
branches:
  except:
    - gh-pages
  only:
    - master