const appConstants = {
  REMOVE_POST: 'REMOVE_POST',
  SET_POSTS: 'SET_POSTS',
  SET_POST: 'SET_POST',
  SET_POST_DATA: 'SET_POST_DATA',
  SET_POSTS_DATA: 'SET_POSTS_DATA',
  SEARCH: 'SEARCH',
  USER_POSTS: 'USER_POSTS',
};

export default appConstants;
